### ISSUE TITLE
automatically exempt ourselves at our own version

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Dist-Zilla-Plugin-CheckPrereqsIndexed#13]
This has been on my todo list for quite some time - I am transcribing it here in the hopes of getting more reminders to JFDI.

A Dist::Zilla plugin frequently depends on itself (via develop prereqs), and if it is running the very code it is about to ship (e.g. via [Bootstrap::lib], or `dzil run`), then CheckPrereqsIndexed can trip up with the complaint that the required version isn't yet indexed (but we the author knows that it's *about* to be, as soon as we do the upload).  Therefore I'd like to remove `( ref($self) => $self->version )` from the list of things being complained about.  The existing skip option isn't sufficient, as I only want to exempt the *current* version, not any version higher than that.  (Perhaps it makes sense to add a version option to `skip`, somehow?)

I'm fine if this is only done with an option that defaults to false; I'd just set it to true in my bundle.

**Comment by karenetheridge** [comment]
I've finally gotten around to doing this in https://github.com/rjbs/Dist-Zilla-Plugin-CheckPrereqsIndexed/pull/21!!!! 👯 💃

**Comment by rjbs** [comment]
:dancers:
