### ISSUE TITLE
Warning in case of dotted alpha release.

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla-Plugin-CheckPrereqsIndexed#24]
My module uses dotted version: 

    our $VERSION = 'v0.11.2_04';

When I try to release it, I see a warning in dzil output:

    Argument "v0.11.2_4" isn't numeric in numeric ge (>=) at .../lib/perl5/Dist/Zilla/Plugin/CheckPrereqsIndexed.pm line 92.

Dist::Zilla::Plugin::CheckPrereqsIndexed 0.020.

**Comment by rjbs** [comment]
How's 46a9e23 for you?

**Comment by van-de-bugger** [comment]
Good.
