### ISSUE TITLE
should also check "optional_feature" entries

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Dist-Zilla-Plugin-CheckPrereqsIndexed#8]
This is a placeholder issue for a patch I intend to write later (ping me when you are closer to paying attention to this module!) -- 'optional_feature' metadata also contains module => version information, and should also be verified by this plugin.

See also [OptionalFeature] which generates such data.

**Comment by karenetheridge** [comment]
I have a fix ready for this too - shockingly it only took 5 minutes to write after I finished with #11. it builds on the refactoring I did there, so let me know if/when you've merged that and I'll rebase and push this up.

**Comment by karenetheridge** [comment]
I pushed it into #22 - just cherry pick the last commit.

**Comment by rjbs** [comment]
thanks, applied!
